# Run docker-compose build
# Run docker-compose up
# Live long and prosper

version: '2'

services:

  nginx:
    container_name: nginx
    image: nginx
    build:
      context: .
      dockerfile: .docker/nginx.dockerfile
    volumes:
      - ./dist:/usr/share/nginx/html
    ports:
      - "80:80"
      - "443:443"

    networks:
      - app-network

  node:
    container_name: nodeapp
    image: nodeapp
    build:
      context: ./microservices/node
      dockerfile: .docker/node.development.dockerfile
    volumes:
      - ./microservices/node:/var/www/angularnoderestfulservice
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on: 
      - postgres
    networks:
      - app-network
      
  #No authentication is provided here - JUST A DEMO! That would absolutely
  #be needed for a "real" application
  postgres:
    container_name: 'postgres'
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5430:5430"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge